_parent_: config/base.yaml

mode:  train                                     # train/test

data:
    base_dir: ./nerf_synthetic
    scene: lego
    type: white_bkgd

model:
    type: hash

test:
    inference_train: False
    ckpt: output/lego/hashnerf_fuck_resolution_newnerf_accmap/ckpt/model7_44000.pth

description: hash_test

old: False