import imageio
import os

def generate_video_from_images(image_directory, output_file='output.mp4', fps=50):
    # List all image files in the directory
    image_files = [os.path.join(image_directory, f) for f in os.listdir(image_directory) if f.endswith(".png")]
    image_files.sort(key=lambda x: os.path.getctime(x)) # NOTE: our png files are generated by timestamp, not by filename, such as 9_0.png && 91_0.png

    # Create an empty list to store the image frames
    frames = []

    # Read each image file and append it to the frames list
    for image_file in image_files:
        frames.append(imageio.imread(image_file))

    # Write the frames to an MP4 video file
    imageio.mimwrite(os.path.join(image_directory, output_file), frames, fps=fps)


if __name__ == '__main__':
    image_directory = "output/lego/hidden128/test"
    output_file = "output.mp4"

    generate_video_from_images(image_directory)
